### ISSUE TITLE
New JUnit 'Run Configurations' cannot resolve SimpleUnitTest

### ISSUE THREAD

**Issue by ebabel** [nenick/AndroidStudioAndRobolectric#1]
Fresh checkout of this project and I can't get it to work. Gradle experimental Unit Test support is enabled.

![screen shot 2015-02-11 at 7 36 15 pm](https://cloud.githubusercontent.com/assets/1874627/6161426/7b431abe-b225-11e4-9615-65681993d94d.png)

Thanks for this project!

**Comment by ebabel** [comment]
Wups, forgot to change the Build Variants! Please disregard

**Comment by nenick** [comment]
I added this step to the getting started part. Thanks for the feedback.

**Comment by baoti** [comment]
:+1:   Enable experimental Unit Test and Change the Build Variants!
Thanks!
