### ISSUE TITLE
Not An Issue

### ISSUE THREAD

**Issue by jpshelley** [nenick/AndroidStudioAndRobolectric#17]
This is not an issue. But I would love to buy you a coffee! I've been banging my head for the past 4 weeks on setting up test suites for library based projects without Activity's. I just got my first passing test case thanks to your repository! :D (Not joking about the coffee, its the least I could do!)

**Comment by nenick** [comment]
Thanks for your kind words.

I will come back on this if I visit USA again and I'm in the near of you ;)
