### ISSUE TITLE
No issue - line #-1 (sorry, not yet implemented): Error inflating class <unknown>

### ISSUE THREAD

**Issue by misrakli** [nenick/AndroidStudioAndRobolectric#18]
Hi,
first thanks a lot for the example project..
I am trying to setup my first test in a android library following your example but I am getting following error when launching the test.

InflateException... line #-1 (sorry, not yet implemented): Error inflating class <unknown>

Any ideas what i am doing wrong ?
Thanks!

**Comment by nenick** [comment]
I need much much more details ;) best would be if you create a github project and show me your current setup. This error looks like you have activities and try to setup them with Robolectric but Robolectric could not find some classes which are referenced in your layout.xml 

But that all are only guesses and I haven't a concrete solution until I got more details.

**Comment by misrakli** [comment]
thank you for your quick reply..
setting up a new project will take time because i have to extract the relevant parts from the project i am currently working on in a company. But i will try to do it the next days..
Maybe these information can give you a hint:

Project directory structure is as follows:

```
myproject
  app
    src
      main
         java
            mypackage
                 MyAppClassjava
         AndroidManifest.xml
         res 
            layout
      test
          java
             mypackage
                 MyTest.java
   build.gradle

myandroidLibrary
    src 
      main
          java
             mylibpackage
                 MyLibActivity.java
          AndroidManifest.xml
          res
            layout
      test
         java 
            mylibpackage
                 MyLibTest.java
   build.gradle

build.gradle
```

Project wide gradle.build

```
buildscript {
    repositories {
        mavenLocal()
        jcenter()
}

dependencies {
    classpath 'com.android.tools.build:gradle:1.1.3'
    classpath 'org.robolectric:robolectric-gradle-plugin:0.14.1'
    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
 }
```

myAndroidLibrary gradle.build

```
android {
   compileSdkVersion 22
   defaultConfig  {
     minSdkVersion 16
     targetSdkVersion 22
  }
 ...
}

android.sourceSets.test.java.srcDirs += "build/generated/source/r/debug"

dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')
  compile 'com.android.support:support-v4:22.0.0'
  compile 'com.google.android.gms:play-services:7.0.0'

  testCompile 'junit:junit:4.12'
  testCompile 'org.mockito:mockito-core:1.10.19'

  testCompile 'org.easytesting:fest:1.0.16'
  testCompile ('com.squareup:fest-android:1.0.+') {
      exclude group: 'com.android.support', module: 'support-v4'
  }
  testCompile('org.robolectric:robolectric:3.0-rc2') {
      exclude group: 'commons-logging', module: 'commons-logging'
      exclude group: 'org.apache.httpcomponents', module: 'httpclient'
  }
}
```

The CustomTestRunner for Robolectric is the same as you provided in your example project.

**Comment by nenick** [comment]
`robolectric-gradle-plugin` will become deprecated when `robolectric 3.0` is final and is not necessary for my setup style. When you want this for some reasons then it's recommend to use version `1.0.1`.

`compileSdkVersion 22` isn't supported yet (it can work but debugging into android code will be hell), try switch to version `21`.

Also add the dependency `testCompile 'org.robolectric:shadows-support-v4:3.0-rc2'` when you use `support-v4`. (I guess that will be the solution for this issue)

How looks your layout file? Maybe you can list your used components in this layout? I guess you use components from `support-v4` or `play-services`.

Create a simple activity with a very simple layout (LinearLayout with TextView) and try if this activity could be setup without issues.

Perhaps you need a more complex setup because of aar dependencies but only if it complain about missing R classes. https://github.com/nenick/AndroidStudioAndRobolectric/tree/library-with-aar

**Comment by nenick** [comment]
Please report your Android Studio version, android gradle plugin version and OS

**Comment by misrakli** [comment]
I followed your suggestion and created a simple Activity with a simple layout. Indeed it works fine. I then put an EditText with the attribute "android:imeActionId". With this change the test fail with the RuntimeException as described above. Removing this attribute, the test runs fine.
In my regular Activity i am using the v4.DrawerLayout and this EditText with imeActionId .

I changed my gradle.build

```
dependencies {
 compile fileTree(include: ['*.jar'], dir: 'libs')
 compile 'com.android.support:support-v4:22.0.0'
 compile 'com.google.android.gms:play-services:7.0.0'

 testCompile 'junit:junit:4.8.2'
 testCompile 'org.mockito:mockito-core:1.10.19'

 testCompile 'org.easytesting:fest:1.0.16'
 testCompile ('com.squareup:fest-android:1.0.+') {
     exclude group: 'com.android.support', module: 'support-v4'
 }
 testCompile('org.robolectric:robolectric:3.0-rc2') {
     exclude group: 'commons-logging', module: 'commons-logging'
     exclude group: 'org.apache.httpcomponents', module: 'httpclient'
  }
 testCompile 'org.robolectric:shadows-support-v4:3.0-rc2'
}
```

Adding 'org.robolectric:shadows-support-v4:3.0-rc2' doesn't help .

**Comment by misrakli** [comment]
changed 
   compile 'org.robolectric:shadows-support-v4:3.0-rc2 
from
   testCompile 'org.robolectric:shadows-support-v4:3.0-rc2'

Android Studio Version 1.1.0 on Win7 , gradle plugin 1.1.3

**Comment by misrakli** [comment]
I tried the 'complex' way as you suggested in your other example. The problem now is that in intermediates\exploded-aar\com.android.support\support-v4\22.1.1 the file R.txt does not exist.

**Comment by nenick** [comment]
The appcompat version was hardcoded for a workaround but now I applied another workaround which should work with each version. In the core/build.gradle you must change the target package to your package name for the copy task. And if you have more aar dependencies, you must add them on the same way.

**Comment by nenick** [comment]
With `android:imeActionId` other users have problem too. See https://github.com/robolectric/robolectric/issues/937

**Comment by misrakli** [comment]
I changed build.gradle as follows:

```
afterEvaluate { project ->
    android.libraryVariants.each { variant ->
    // workaround for missing R class for aar dependencies
    tasks.getByName("assemble${variant.name.capitalize()}").dependsOn copyAppcompat

    // workaround for missing compilation of main sources
    tasks.getByName("test${variant.name.capitalize()}") {
        dependsOn "assemble${variant.name.capitalize()}"
    }
}
}

task copyAppcompat(type: Copy) {
  from 'build/generated/source/r/debug/com/my/package'
  into 'build/generated/source/r/debug/android/support/v4/support'
  include 'R.java'
  filter { line -> line.contains('package com.my.package') ? 'package android.support.v4.support;' : line }
}
```

I also followed the suggestions relating to the problem with android:imeActionId  and it works !!!
For now i can write and run simple tests. The next problem is sure waiting for me, but for now i have a starting point .... Thank you so much !!
One thing for my understanding: why have we to copy our R.java file to the support-v4 destination, what is the background for this problem?

**Comment by nenick** [comment]
hard to explain ... The base issue is how android generates the R classes. For application module all R classes are generated but for library modules only the "main" R class. And robolectic needs them all to work. The issue is tracked at https://github.com/robolectric/robolectric/issues/1737
