### ISSUE TITLE
Package R does not exist

### ISSUE THREAD

**Issue by nenick** [nenick/AndroidStudioAndRobolectric#6]
The issue is tracked here https://code.google.com/p/android/issues/detail?id=144573 

A workaround is to add following line to the module build.gradle
`android.sourceSets.test.java.srcDirs += "build/generated/source/r/debug"`

**Comment by emartynov** [comment]
Thanks for sharing!

**Comment by nenick** [comment]
Fixed with gradle android plugin 1.2.+
